/// Golden vector tests for tick-math.
///
/// Vectors are generated by tools/golden-vector-gen/generate.ts using the
/// official @pendle/boros-offchain-math SDK. Regenerate them if the SDK changes:
///
///   cd tools/golden-vector-gen && npx ts-node generate.ts > vectors.json
///   cp vectors.json ../../crates/tick-math/tests/vectors.json
///
/// If this test fails it means our Rust math diverges from the on-chain
/// SDK. Fix the Rust, not the vectors.

use serde::Deserialize;
use tick_math::{tick_to_rate, rate_to_tick, Rounding};

#[derive(Deserialize)]
struct Vector {
    tick: i16,
    tick_step: u8,
    /// Rate as a raw i128 string (preserves full FixedX18 precision over JSON)
    rate_raw: String,
    /// Rate as f64 for human-readable tolerance checking
    rate_f64: f64,
}

fn load_vectors() -> Vec<Vector> {
    // If the JSON file exists (generated by the TS script), use it.
    // Otherwise fall back to the embedded vectors below, keeps CI green
    // even without Node.js available.
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/vectors.json");

    if path.exists() {
        let s = std::fs::read_to_string(&path)
            .expect("failed to read vectors.json");
        serde_json::from_str(&s).expect("failed to parse vectors.json")
    } else {
        // embedded fallback, computed from the formula, not from the SDK.
        // SDK-generated file takes priority when present.
        serde_json::from_str(EMBEDDED_VECTORS).expect("embedded vectors malformed")
    }
}

// Computed from 1.00005^(|tick|*step) - 1 using high-precision arithmetic.
// These will be overwritten by the TS generator output when present.
//
// Format: [{ tick, tick_step, rate_raw, rate_f64 }, ...]
// Verified with: python3 -c "import math; ..."
// Do NOT adjust these to match a failing test. Fix the Rust, not the vectors.
const EMBEDDED_VECTORS: &str = r#"[
  { "tick":     0, "tick_step": 1, "rate_raw":                          "0", "rate_f64":  0.0              },
  { "tick":     0, "tick_step": 2, "rate_raw":                          "0", "rate_f64":  0.0              },
  { "tick":     1, "tick_step": 1, "rate_raw":              "50000000000106", "rate_f64":  0.00005000000000 },
  { "tick":   100, "tick_step": 1, "rate_raw":          "5012395237041778",  "rate_f64":  0.005012395237   },
  { "tick":   100, "tick_step": 2, "rate_raw":         "10049914580095854",  "rate_f64":  0.010049914580   },
  { "tick":  -100, "tick_step": 2, "rate_raw":        "-10049914580095854",  "rate_f64": -0.010049914580   },
  { "tick":  1000, "tick_step": 2, "rate_raw":        "105168155244133248",  "rate_f64":  0.105168155244   },
  { "tick": -1000, "tick_step": 2, "rate_raw":       "-105168155244133248",  "rate_f64": -0.105168155244   },
  { "tick": 10000, "tick_step": 2, "rate_raw":      "1718213874533618944",   "rate_f64":  1.718213874534   },
  { "tick": 32767, "tick_step": 1, "rate_raw":      "4146459706326753792",   "rate_f64":  4.146459706327   }
]"#;

#[test]
fn tick_to_rate_matches_sdk() {
    let vectors = load_vectors();
    let tol_relative = 1e-6; // 1 ppm, tight enough to catch formula drift

    for v in &vectors {
        let got = tick_to_rate(v.tick, v.tick_step)
            .unwrap_or_else(|e| panic!("tick_to_rate({}, {}) failed: {e}", v.tick, v.tick_step));

        // f64 check first, human-readable failure
        let diff = (got.to_f64() - v.rate_f64).abs();
        let tol_abs = v.rate_f64.abs() * tol_relative + 1e-14; // abs floor for near-zero rates
        assert!(
            diff <= tol_abs,
            "tick={} step={}: got {:.12} expected {:.12} (diff={:.2e})",
            v.tick, v.tick_step, got.to_f64(), v.rate_f64, diff
        );

        // raw i128 check, catches sign or scale bugs the f64 check might miss
        let expected_raw: i128 = v.rate_raw.parse().expect("malformed rate_raw");
        // allow ±1 ULP at the FixedX18 level
        let raw_diff = (got.inner() - expected_raw).abs();
        assert!(
            raw_diff <= 1_000_000_000, // 1e9 raw = 1e-9 in rate, generous
            "tick={} step={}: raw got {} expected {} (diff {})",
            v.tick, v.tick_step, got.inner(), expected_raw, raw_diff
        );
    }
}

#[test]
fn rate_to_tick_roundtrip() {
    // For every vector, convert rate → tick and check we land within ±1 tick
    // of the original. This tests that our inverse is consistent with our forward.
    let vectors = load_vectors();

    for v in &vectors {
        if v.tick == 0 { continue; } // zero rate has ambiguous direction

        let rate = tick_to_rate(v.tick, v.tick_step).unwrap();

        let rounding = if v.tick > 0 { Rounding::Floor } else { Rounding::Ceil };
        let back = rate_to_tick(rate, v.tick_step, rounding)
            .unwrap_or_else(|e| panic!("rate_to_tick failed for tick={}: {e}", v.tick));

        let drift = (v.tick - back).abs();
        assert!(
            drift <= 1,
            "roundtrip drift tick={} step={}: got back {back} (drift={drift})",
            v.tick, v.tick_step
        );
    }
}
